In [1]:
import numpy as np
import tensorflow as tf

Tensor 생성

- tf.constant()
  - list -> Tensor
  - array - >Tensor

In [5]:
tf.constant([1,2,3])
tf.constant(((1,2,3,),(1,2,3)))


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3]], dtype=int32)>

In [6]:
arr = np.array(np.random.randint(5, size = 10))

In [7]:
tensor = tf.constant(arr)
tensor

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([4, 0, 1, 0, 0, 1, 2, 1, 4, 4])>

shape 확인

In [8]:
tensor.shape

TensorShape([10])

data type 확인
  - 주의: tensor 생성 할 때도 data type을 정해주지 않기 때문에 data type에 대한 혼동이 올 수 있음
  - data type에 따라 모델의 무게나 성능 차이에도 영향을 줄 수 있음

In [9]:
tensor.dtype

tf.int64

data type 정의

In [12]:
tf.constant(arr, dtype=tf.float32)

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([4., 0., 1., 0., 0., 1., 2., 1., 4., 4.], dtype=float32)>

data type 변환
  - numpy에서  astype()을 주었듯이, tensorflow에서는 tf.cast 사용

In [13]:
arr = np.array([1,2,3], dtype=np.float32)

In [14]:
arr.astype(np.uint32)

array([1, 2, 3], dtype=uint32)

In [15]:
tensor

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([4, 0, 1, 0, 0, 1, 2, 1, 4, 4])>

In [19]:
tf.cast(tensor, dtype=tf.uint8)

<tf.Tensor: shape=(10,), dtype=uint8, numpy=array([4, 0, 1, 0, 0, 1, 2, 1, 4, 4], dtype=uint8)>

Tensor에서 numpy 불러오기
  - .numpy

In [23]:
tensor.numpy()

array([4, 0, 1, 0, 0, 1, 2, 1, 4, 4])

In [24]:
np.array(tensor)

array([4, 0, 1, 0, 0, 1, 2, 1, 4, 4])

In [25]:
type(tensor.numpy())

numpy.ndarray

난수 생성
  - normal distribution 은 중심극한 이론에 의한 연속적인 모양
  - uniform distribution은 중심 극한 이론과는 무고나하며 불연속적이며 일정한 분포
  

- numpy에서는 normal distribution을 기본적으로 생성
  - np.random.randn()

In [26]:
np.random.randn(3)

array([-0.24942792,  0.14409483, -0.07989266])

tf.random.noraml
  - tensorflow에서는 normal distribution

In [28]:
tf.random.normal([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.4155763 , -0.08018892, -0.9319324 ],
       [-0.55132943,  0.556652  , -0.4990747 ],
       [-0.6676948 ,  0.24275999, -1.8915713 ]], dtype=float32)>

tf.random.uniform
  - tensorflow에서는 uniform distribution

In [29]:
tf.random.uniform([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.5707923 , 0.5876421 , 0.44642234],
       [0.2771753 , 0.35340405, 0.2654302 ],
       [0.2478323 , 0.1929977 , 0.24878609]], dtype=float32)>